"""Independent native fixtures: exact source-to-object checks for 10x spatial readers.

No fixture is generated by a Spateo writer. Direct readers retain their documented
Gene Expression selection; automatic reading preserves every source feature.
"""

import gzip
import json

import h5py
import numpy as np
import pandas as pd
import pytest
from anndata import read_h5ad
from PIL import Image
from scipy import sparse

from spateo.io import (
    read_atera,
    read_spatial,
    read_visium,
    read_visium_hd_bin,
    read_visium_hd_seg,
    read_xenium,
)

KINDS = ("visium", "visium_legacy", "hd_h5", "hd_mex", "hd_seg", "xenium_csv", "xenium_parquet", "atera")
COUNTS = np.array([[2**24 + 1, 0, 3], [7, 2, 0], [1, 4, 9]], dtype=np.int32)
GENES = ["stable-A", "stable-B", "stable-C"]
NAMES = ["Shared", "Shared", "Unique"]
XY = np.array([[2**24 + 0.25, 1.125], [4.375, 5.625], [8.875, 9.125]], dtype=np.float64)
PIXELS = np.arange(60, dtype=np.uint8).reshape(4, 5, 3)


def _h5(path, ids, control=False):
    matrix = sparse.csc_matrix(COUNTS.T)
    with h5py.File(path, "w") as handle:
        group = handle.create_group("matrix")
        for key, values in (
            ("data", matrix.data),
            ("indices", matrix.indices),
            ("indptr", matrix.indptr),
            ("shape", matrix.shape),
            ("barcodes", np.asarray(ids, dtype="S")),
        ):
            group.create_dataset(key, data=values)
        features = group.create_group("features")
        for key, values in (
            ("id", GENES),
            ("name", NAMES),
            (
                "feature_type",
                ["Gene Expression", "Gene Expression", "Negative Control Probe" if control else "Gene Expression"],
            ),
            ("genome", ["mm10"] * 3),
        ):
            features.create_dataset(key, data=np.asarray(values, dtype="S"))


def _mex(path, ids):
    path.mkdir()
    entries = [(j + 1, i + 1, int(COUNTS[i, j])) for i in range(3) for j in range(3) if COUNTS[i, j]]
    text = "%%MatrixMarket matrix coordinate integer general\n3 3 %d\n" % len(entries)
    text += "".join(f"{g} {c} {v}\n" for g, c, v in entries)
    for name, content in (
        ("matrix.mtx", text),
        ("barcodes.tsv", "\n".join(ids) + "\n"),
        ("features.tsv", "".join(f"{gid}\t{symbol}\tGene Expression\n" for gid, symbol in zip(GENES, NAMES))),
    ):
        with gzip.open(path / (name + ".gz"), "wt") as stream:
            stream.write(content)


def _fixture(tmp_path, kind, *, issue=None, control=False):
    root = tmp_path / ("square_016um" if kind.startswith("hd_") and kind != "hd_seg" else kind)
    root.mkdir()
    ids = [f"cellid_{i:09d}-1" for i in range(1, 4)] if kind == "hd_seg" else ["bc-A", "bc-B", "bc-C"]
    if kind == "hd_mex":
        _mex(root / "filtered_feature_bc_matrix", ids)
    else:
        name = (
            "filtered_feature_cell_matrix.h5"
            if kind == "hd_seg"
            else (
                "cell_feature_matrix.h5"
                if kind.startswith("xenium") or kind == "atera"
                else "filtered_feature_bc_matrix.h5"
            )
        )
        _h5(root / name, ids, control=control)
    source_xy = XY.copy()
    if issue == "nonfinite":
        source_xy[1, 0] = np.nan
    order = [2, 0, 1]
    if issue == "missing":
        order = [2, 0]
    elif issue == "duplicate":
        order = [2, 0, 1, 1]
    if kind == "hd_seg":
        features = []
        for i in order:
            x, y = source_xy[i]
            corners = [
                [x - 0.25, y - 0.25],
                [x + 0.25, y - 0.25],
                [x + 0.25, y + 0.25],
                [x - 0.25, y + 0.25],
                [x - 0.25, y - 0.25],
            ]
            features.append(
                {
                    "type": "Feature",
                    "properties": {"cell_id": i + 1},
                    "geometry": {"type": "Polygon", "coordinates": [corners]},
                }
            )
        (root / "graphclust_annotated_cell_segmentations.geojson").write_text(
            json.dumps({"type": "FeatureCollection", "features": features})
        )
    elif kind.startswith("xenium") or kind == "atera":
        cells = pd.DataFrame(
            {
                "cell_id": [ids[i] for i in order],
                "x_centroid": [source_xy[i, 0] for i in order],
                "y_centroid": [source_xy[i, 1] for i in order],
                "cell_area": [42.5] * len(order),
            }
        )
        if kind == "xenium_parquet":
            cells.to_parquet(root / "cells.parquet", index=False)
        else:
            cells.to_csv(root / "cells.csv.gz", index=False)
        (root / "experiment.xenium").write_text(
            json.dumps({"platform": "Atera" if kind == "atera" else "Xenium", "pixel_size": 0.25})
        )
        import tifffile

        img = PIXELS[:, :, 0]
        if kind == "atera":
            (root / "morphology_focus").mkdir()
            tifffile.imwrite(root / "morphology_focus/ch0000_dapi.ome.tif", img)
        else:
            tifffile.imwrite(root / "morphology_focus.ome.tif", img)
    else:
        (root / "spatial").mkdir()
        pos = pd.DataFrame(
            [[ids[i], 1, i, i + 1, source_xy[i, 1], source_xy[i, 0]] for i in order],
            columns=["barcode", "in_tissue", "array_row", "array_col", "pxl_row_in_fullres", "pxl_col_in_fullres"],
        )
        if kind == "visium_legacy":
            pos.to_csv(root / "spatial/tissue_positions_list.csv", index=False, header=False)
        elif kind.startswith("hd_"):
            pos.to_parquet(root / "spatial/tissue_positions.parquet", index=False)
        else:
            pos.to_csv(root / "spatial/tissue_positions.csv", index=False)
    spatial = root / "spatial"
    spatial.mkdir(exist_ok=True)
    Image.fromarray(PIXELS).save(spatial / "tissue_hires_image.png")
    (spatial / "scalefactors_json.json").write_text(
        json.dumps({"tissue_hires_scalef": 0.5, "spot_diameter_fullres": 25})
    )
    return root, ids


def _direct(root, kind):
    if kind.startswith("visium"):
        return read_visium(root)
    if kind in ("hd_h5", "hd_mex"):
        return read_visium_hd_bin(root)
    if kind == "hd_seg":
        return read_visium_hd_seg(root)
    if kind.startswith("xenium"):
        return read_xenium(root)
    return read_atera(root)


def _check(adata, ids, counts=COUNTS, gene_ids=GENES):
    assert adata.obs_names.tolist() == ids
    assert adata.var["gene_ids"].tolist() == gene_ids
    np.testing.assert_array_equal(adata.X.toarray(), counts)
    np.testing.assert_array_equal(adata.obsm["spatial"], XY)


@pytest.mark.parametrize("kind", KINDS)
def test_auto_direct_exact_source_values_and_roundtrip(tmp_path, kind):
    root, ids = _fixture(tmp_path, kind)
    result = read_spatial(root)
    auto, direct = result.adata, _direct(root, kind)
    expected_tech = (
        "visium_hd_cellseg"
        if kind == "hd_seg"
        else (
            "visium_hd_bin"
            if kind.startswith("hd_")
            else "xenium" if kind.startswith("xenium") else "visium" if kind.startswith("visium") else "atera"
        )
    )
    assert next(iter(result.datasets.values())).technology == expected_tech
    for i, adata in enumerate((auto, direct)):
        _check(adata, ids)
        assert adata.var_names.tolist() == NAMES
        path = tmp_path / f"roundtrip-{i}.h5ad"
        adata.write_h5ad(path)
        _check(read_h5ad(path), ids)
    direct_slot = next(iter(direct.uns["spatial"].values()))
    auto_slot = next(iter(auto.uns["spatial"].values()))
    expected_image = PIXELS[:, :, 0] if kind.startswith("xenium") or kind == "atera" else PIXELS
    np.testing.assert_array_equal(direct_slot["images"]["hires"], expected_image)
    assert any(np.array_equal(image, expected_image) for image in auto_slot["images"].values())


@pytest.mark.parametrize("kind", KINDS)
@pytest.mark.parametrize("issue", ("missing", "duplicate", "nonfinite"))
def test_invalid_core_metadata_is_rejected_without_silent_cell_loss(tmp_path, kind, issue):
    root, _ = _fixture(tmp_path, kind, issue=issue)
    result = read_spatial(root)
    assert not any(entry.adata is not None for entry in result.datasets.values())
    assert all(entry.status == "failed" for entry in result.datasets.values())
    with pytest.raises((ValueError, KeyError)):
        _direct(root, kind)


@pytest.mark.parametrize("kind", KINDS)
def test_direct_does_not_call_automatic_reader(tmp_path, kind, monkeypatch):
    import spateo.io.spatial.auto._automatic as automatic

    root, ids = _fixture(tmp_path, kind)

    def forbidden(*args, **kwargs):
        raise AssertionError("Direct reader called automatic entry point")

    monkeypatch.setattr(automatic, "read_spatial", forbidden)
    _check(_direct(root, kind), ids)


@pytest.mark.parametrize("kind", ("visium", "hd_h5", "hd_seg", "xenium_csv", "atera"))
def test_documented_gene_expression_selection(tmp_path, kind):
    root, ids = _fixture(tmp_path, kind, control=True)
    auto, direct = read_spatial(root).adata, _direct(root, kind)
    _check(auto, ids)
    _check(direct, ids, COUNTS[:, :2], GENES[:2])
    assert auto.var["feature_types"].iloc[-1] == "Negative Control Probe"


@pytest.mark.parametrize("kind", ("visium", "hd_h5", "hd_mex", "hd_seg"))
def test_corrupt_optional_image_keeps_core(tmp_path, kind):
    root, ids = _fixture(tmp_path, kind)
    (root / "spatial/tissue_hires_image.png").write_bytes(b"not an image")
    _check(read_spatial(root).adata, ids)
    with pytest.warns(UserWarning):
        _check(_direct(root, kind), ids)


@pytest.mark.parametrize("kind", KINDS)
@pytest.mark.parametrize("bad_count", (-1, 0.5))
def test_invalid_raw_counts_are_rejected(tmp_path, kind, bad_count):
    root, _ = _fixture(tmp_path, kind)
    if kind == "hd_mex":
        path = root / "filtered_feature_bc_matrix/matrix.mtx.gz"
        with gzip.open(path, "rt") as stream:
            text = stream.read()
        text = text.replace("integer general", "real general").replace(str(2**24 + 1), str(bad_count))
        with gzip.open(path, "wt") as stream:
            stream.write(text)
    else:
        path = next(root.glob("*.h5"))
        with h5py.File(path, "a") as handle:
            values = handle["matrix/data"][:].astype(float)
            values[0] = bad_count
            del handle["matrix/data"]
            handle["matrix"].create_dataset("data", data=values)
    result = read_spatial(root)
    assert all(entry.status == "failed" and entry.adata is None for entry in result.datasets.values())
    with pytest.raises(ValueError):
        _direct(root, kind)


@pytest.mark.parametrize("kind", KINDS)
def test_missing_required_metadata_file_fails_clearly(tmp_path, kind):
    root, _ = _fixture(tmp_path, kind)
    if kind == "hd_seg":
        (root / "graphclust_annotated_cell_segmentations.geojson").unlink()
    elif kind.startswith("xenium") or kind == "atera":
        next(root.glob("cells.*")).unlink()
    else:
        next((root / "spatial").glob("tissue_positions*")).unlink()
    result = read_spatial(root)
    assert all(entry.status == "failed" and entry.adata is None for entry in result.datasets.values())
    with pytest.raises(FileNotFoundError):
        _direct(root, kind)
